### ISSUE TITLE
Extetion is delete on VSCode

### ISSUE THREAD

**Issue by NightMira** [rsKliPPy/amxxpawn-language#24]
I don't found extension on marketplace

![image](https://github.com/rsKliPPy/amxxpawn-language/assets/126119211/09c012ed-ea5a-4399-953c-2f2c2fb916aa)

**Comment by Nord1cWarr1or** [comment]
It's not removed, but for some reason (idk) it doesn't show up in the extension store if you use the free VSCode version. I ran into the same problem on Linux.
The installation can be done via the .vsix file by downloading it here:  https://marketplace.visualstudio.com/items?itemName=KliPPy.amxxpawn-language&ssr=false#version-history

**Comment by NightMira** [comment]
This extetion don't show on OS Linux


> It's not removed, but for some reason it doesn't show up in the extension store if you use the free VSCode version. I ran into the same problem on Linux. The installation can be done via the .vsix file by downloading it here: https://marketplace.visualstudio.com/items?itemName=KliPPy.amxxpawn-language&ssr=false#version-history

Thx you!
