### ISSUE TITLE
Bug with 'Go to Definition/Peek Definition'

### ISSUE THREAD

**Issue by RevCrew77** [rsKliPPy/amxxpawn-language#3]
When I update to latest version function 'Go to Definition/Peek Definition'  was not work
![image](https://user-images.githubusercontent.com/11967977/37487202-e9928c5c-28a1-11e8-9ef9-dbd7284055a7.png)

**Comment by rsKliPPy** [comment]
Thanks, I'll check it out tomorrow.

**Comment by rsKliPPy** [comment]
Thanks for filing a bug report. I've published the fix.
