### ISSUE TITLE
Enum improvement

### ISSUE THREAD

**Issue by Mistrick** [rsKliPPy/amxxpawn-language#4]
Can you add support for first case?
![asdasdasdasd](https://user-images.githubusercontent.com/4307674/37610499-4f5c4036-2bd2-11e8-8221-286c5dd7bc05.PNG)

**Comment by rsKliPPy** [comment]
Thank you, I fixed it and published the update.

**Comment by Mistrick** [comment]
Now I have this.
![image](https://user-images.githubusercontent.com/4307674/37616928-04b25b76-2be4-11e8-96c1-ac64b8565fc5.png)

**Comment by rsKliPPy** [comment]
Should be fixed for real now. Totally forgot about unnamed enumerations.

**Comment by Mistrick** [comment]
Wrong detection in case.
![image](https://user-images.githubusercontent.com/4307674/39516071-0680c76c-4e26-11e8-8740-6b6455f65a37.png)
