### ISSUE TITLE
bug with highlighting comments (white color)

### ISSUE THREAD

**Issue by RevCrew77** [rsKliPPy/amxxpawn-language#7]
![image](https://user-images.githubusercontent.com/11967977/37826645-4f0abd1c-2ea5-11e8-8bea-d568c2ac5054.png)

**Comment by rsKliPPy** [comment]
Actually the "summary" is colored - it's the part of the comment before any `@param`, `@note` etc. that briefly explains the function. I was also thinking about it and I may just remove the coloring on it, it's too colorful.

**Comment by RevCrew77** [comment]
Ok
